name: Compatibility tests

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compatibility-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Update and install libglu1-mesa (Ubuntu only)
        run: |
          sudo apt update
          sudo apt-get install -y libglu1-mesa
        if: runner.os == 'Linux'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run test script
        run: python -m pytest -v tests/compatibility